modLoader = "kotlinforforge"
loaderVersion = "${loaderVersionRange}"
#issueTrackerURL = ""
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthors}"
description = '''
${modDescription}
'''
logoFile = "logo.png"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${modId}.mixins.json"
